## WARNING
## This file was autogenerated, and _will_ be overwritten by Halyard.
## Any edits you make here _will_ be lost.

wget --header="content-type: application/json"  --post-data='{"enabled": "false"}' http://localhost:8083/admin/instance/enabled

sleep 30
