on:
  push:
    branches:
    - main
    - release-*
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic
jobs:

  build-igor:
    outputs:
      igor: ${{ steps.get-build-name.outputs.igor }}
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpsMx igor repo
      uses: actions/checkout@v3
      with:
        repository: yugaa22/igor
        ref: refs/heads/master
    - name: check for changes
      run: |
       if [ $(git log --since="$(date) 00:00:00" --format=%H) ]; then 
           echo "There are changes for today $date"
           git log --since="$(date) 00:00:00" --format=%H           
          #echo "{name}={CHANGES_EXISTS::true}" >> $GITHUB_OUTPUT 
          echo "{CHANGES_EXISTS}={true}" >> $GITHUB_OUTPUT 

          #echo "CHANGES_EXISTS=true"  
         else
           echo "No Changes for today $date"
           git log --since="$(date) 00:00:00" --format=%H
           echo "{name}={CHANGES_EXISTS::false}" >> $GITHUB_OUTPUT 
           echo "CHANGES_EXISTS=false"       
         fi      
         
         echo "now env is" ${{ env.CHANGES_EXISTS }}
    - uses: actions/setup-java@v3 
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      with:
        distribution: temurin
        java-version: 17
        cache: 'gradle'
  outputs:
    runs-on: ubuntu-latest
    needs: [build-igor]
    steps:
    - name: Che4ck out repository code
      uses: actions/checkout@v3
    - run: | 
          cp bom bom-old
          
          yq ${{ needs.build-echo.outputs.echo }} > bom

          yq ${{ needs.build-igor.outputs.igor }} > bom
          
          #yq e -i '.deploymentConfigurations[0].version = "1.30.1"' config 
 
          git config --global user.email "yugaa22@gmail.com"
          git config --global user.name "yugaa22"
          git add .
          git commit -m "updating master Branch images into service settings"
          git push
      env:
         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
