on:
  push:
    branches:
    - main
    - release-*
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic
jobs:

  build-igor:
    outputs:
      igor: ${{ steps.get-build-name.outputs.igor }}
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpsMx igor repo
      uses: actions/checkout@v3
      with:
        repository: yugaa22/igor-oes
        ref: refs/heads/OES-1.30.x
    - name: check for changes
      run: |
       if [ $(git log --since="$(date) 00:00:00" --format=%H) ]; then 
           echo "There are changes for today $date"
           git log --since="$(date) 00:00:00" --format=%H         
           echo "CHANGES_EXISTS=true" >> $GITHUB_ENV
         else
           echo "No Changes for today $date"
           git log --since="$(date) 00:00:00" --format=%H
           echo "CHANGES_EXISTS=false" >> $GITHUB_ENV
         fi      
    - uses: actions/setup-java@v3 
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      with:
        distribution: zulu
        java-version: 11
        cache: 'gradle'
    - name: Set up QEMU
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      uses: docker/setup-buildx-action@v2
    - name: Prepare build variables
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      id: build_variables
      run: |
          echo ::set-output name=REPO::"ubi8-igor-cve"
          echo ::set-output name=VERSION::"$(git rev-parse --short HEAD)-$(date --utc +'%Y%m%d%H%M')"
    - name: Build
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      run: ./gradlew --no-daemon -PenableCrossCompilerPlugin=true igor-web:installDist -x test
    - name: Login to Quay
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.ARTIFACTORY_USERNAME }}
        password: ${{ secrets.ARTIFACTORY_KEY }}
    - name: dockerBuildpush
      if: ${{ env.CHANGES_EXISTS == 'true' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: docker/ubi8/Dockerfile-dev
        push: true
        tags: |
          "${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}"
    - name: get-build-name
      run: |    
        echo  "output is" ${{ env.CHANGES_EXISTS }} 
        
    - if: ${{ env.CHANGES_EXISTS == 'true' }}
      run: |
           imageName=${{ env.CONTAINER_REGISTRY }}/${{ steps.build_variables.outputs.REPO }}:${{ steps.build_variables.outputs.VERSION }}
             echo "true condition"
            echo "igor=$imageName" >> $GITHUB_OUTPUT
    - if: ${{ env.CHANGES_EXISTS == 'false' }}
      uses: actions/checkout@v3
    - run: |
         yq '.services.igor.img' bom
         echo "false condition"
         imageName=$(yq '.services.igor.img' bom
         echo "igor=$imageName" >> $GITHUB_OUTPUT
          
  outputs:
    runs-on: ubuntu-latest
    needs: [build-igor]
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: | 
    
         ls -ltra
         
          cp bom bom-old
          
          yq e -i '.services.igor.img = ${{ needs.build-igor.outputs.igor }}' bom 

          #yq ${{ needs.build-igor.outputs.igor }} > bom
          
          #yq e -i '.deploymentConfigurations[0].version = "1.30.1"' config 
 
          git config --global user.email "yugaa22@gmail.com"
          git config --global user.name "yugaa22"
          git add .
          git commit -m "updating master Branch images into service settings"
          git push
      env:
         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
