name: List Namespaces
on:
  push:
    branches:
      - main

jobs:
  list-namespaces:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: List Namespaces
        run: kubectl get namespaces
