name: Setup Spinnaker
on:
  push:
    branches:
      - main
jobs:
  OpsMx-Spinnaker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Kubernetes
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIGTEST }}

      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Add Helm repository
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add spinnaker https://opsmx.github.io/spinnaker-helm/
          helm repo update
          
      - name: Setup OpsMx Helm chart and Install
        run: |
          
           kubectl create ns spinnaker
            
           kubectl -n spinnaker create secret generic opsmx-gitops-auth  --from-literal=gitcloneparam='${{ secrets.GIT_ACCOUNT_DATA }}' --from-literal=gituser=yugaa22 --from-literal=gittoken='${{ secrets.GIT_TOKEN }}'
          
           helm upgrade --install spinnaker spinnaker/spinnaker --set halyard.gitops.enabled=true --timeout 600s -n spinnaker

