name: Install Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Kubernetes cluster
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Add Helm repository
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add spinnaker https://opsmx.github.io/spinnaker-helm/
          helm repo update
          kubectl get ns

      - name: Install Helm chart
        run: |
          
          helm upgrade --install oss-spin spinnaker/spinnaker -n opsmx-oss --timeout 600s --create-namespace
