name: Setup localspins
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      namespace:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Spinnaker namespace'
        # Default value if no value is explicitly provided
        default: 'yugatest'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string
      releasename:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Helm Release'
        # Default value if no value is explicitly provided
        default: 'oss-yuga'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string
        
jobs:
  OpsMx-Spinnaker:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Display structure of downloaded files
      
        env:
          MY_SECRET: ${{ secrets.GIT_TOKEN }}
        run: |
          echo "The value of MY_SECRET_NAME is $MY_SECRET"
           pwd
                  echo $MY_SECRET >> secrets.txt

                  
           pwd
            #ls -ltra


            echo ${{inputs.releasename}}
            echo ${{secrets.GIT_USERNAME}}

            echo cloneparam='https://'${{ secrets.GIT_USERNAME }}':'${{ secrets.GIT_TOKEN_TEST }}'@github.com/'${{ secrets.organisation }}'/'${{ secrets.repository }}'.git'

            
           export KUBECONFIG=ninja-training-cluster.config
           #kubectl get ns
           
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2

      - name: Install Helm
        run: |
          curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Add Helm repository
        run: |
          helm repo add stable https://charts.helm.sh/stable 
          helm repo add spinnaker https://opsmx.github.io/spinnaker-helm/ 
          helm repo update 
          
      - name: Setup OpsMx Helm chart and Install
        run: |
           export KUBECONFIG=ninja-training-cluster.config
           kubectl get ns

           kubectl create ns ${{ inputs.namespace}} 

           #https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN_TEST }}@github.com/${{ secrets.organisation }}/${{ secrets.repository }}.git

           echo "cloneparam='https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN_TEST }}@github.com/${{ secrets.organisation }}/${{ secrets.repository }}.git' 
            
           #kubectl -n ${{ inputs.namespace}} create secret generic opsmx-gitops-auth  --from-literal=gitcloneparam='https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN_TEST }}@github.com/${{ secrets.organisation }}/${{ secrets.repository }}.git' --from-literal=gituser=${{ secrets.GIT_USERNAME }} --from-literal=gittoken='${{ secrets.GIT_TOKEN }}'
          
           #helm -n ${{ inputs.namespace}} upgrade --install  ${{ inputs.releasename}} spinnaker/spinnaker --set halyard.gitops.enabled=true --set spinnakerVersion=1.30.1 --timeout 600s
