on:
  push:
    branches:
    - main
    - release-*
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx6g -Xms6g
  CONTAINER_REGISTRY: quay.io/opsmxpublic
jobs:

  outputs:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git config
      run: |
          git config --global user.email "yugaa22@gmail.com"
          git config --global user.name "yugaa22"

    - name: Clone target repo
      run: |
          git clone --depth 1 https://github.com/yugaa22/cve-target.git target-repo
  
    - name: Copy files     
      working-directory: ./target-repo
      run: | 
          pwd

          ls -ltra
           
          ls -ltra default/service-settings

          touch default/service-settings/rosco.yml
          
          echo artifactId:  > default/service-settings/rosco.yml
            
          git add .
          
          git commit -m "updating master Branch images into service settings"
          
          git remote set-url origin https://yugaa22:${{ secrets.GIT_TOKEN }}@github.com/yugaa22/cve-target.git
          
          git push
      env:
         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    - run: echo "🍏 This job's status is ${{ job.status }}."

